apiVersion: cluster.k8s.io/v1alpha1
kind: Cluster
metadata:
  name: CLUSTER_NAME
  namespace: NAMESPACE
  labels:
    kaas.mirantis.com/provider: equinixmetalv2
    kaas.mirantis.com/region: region-one
spec:
  clusterNetwork:
    services:
      cidrBlocks:
        - 172.21.0.0/18
    pods:
      cidrBlocks:
        - 172.21.128.0/17
  providerSpec:
    value:
      apiVersion: equinix.kaas.mirantis.com/v1alpha2
      kind: EquinixMetalClusterProviderSpec
      facility: EQUINIX_FACILITY
      dedicatedControlPlane: DEDICATED_CONTROL_PLANE
      credentials: cloud-config
      release: CLUSTER_RELEASE
      ceph:
        manualConfiguration: CEPH_MANUAL_CONFIGURATION
      helmReleases:
      - name: stacklight
        values:
          alertmanagerSimpleConfig:
            email:
              enabled: false
            salesForce:
              enabled: false
            slack:
              enabled: false
          highAvailabilityEnabled: false
          logging:
            enabled: false
            level: INFO
          prometheusServer:
            customAlerts: []
            persistentVolumeClaimSize: 16Gi
            retentionSize: 15GB
            retentionTime: 15d
            watchDogAlertEnabled: false
          sfReporter:
            enabled: false
          stacklightLogLevels:
            component: {}
            default: null
      network:
        vlanId: "SET_EQUINIX_VLAN_ID"
        additionalVlans:
        - id: "SET_FIP_VLAN_ID"
        loadBalancerHost: SET_LB_HOST
        metallbRanges:
          - SET_EQUINIX_METALLB_RANGES
        cidr: SET_EQUINIX_NETWORK_CIDR
        gateway: SET_EQUINIX_NETWORK_GATEWAY
        dhcpRanges:
          - SET_EQUINIX_NETWORK_DHCP_RANGES
        includeRanges:
          - SET_EQUINIX_CIDR_INCLUDE_RANGES
        excludeRanges:
          - SET_EQUINIX_CIDR_EXCLUDE_RANGES
        nameservers:
          - SET_EQUINIX_NETWORK_NAMESERVERS
      publicKeys:
      - name: bootstrap-key
      projectSSHKeys:
      - "EQUINIX_SSH_KEY_NAME"
      kaas:
        management:
          enabled: false
