apiVersion: lcm.mirantis.com/v1alpha1
kind: OpenStackDeployment
metadata:
  name: osh-dev
  namespace: openstack
spec:
  draft: false
  openstack_version: victoria
  preset: compute
  size: tiny
  internal_domain_name: cluster.local
  public_domain_name: it.just.works
  features:
    services:
    - object-storage
    - tempest
    neutron:
      tunnel_interface: bond0.1001
      dvr:
        enabled: false
      external_networks:
      - physnet: physnet1
        interface: bond0.1002
        bridge: br-ex
        network_types:
        - flat
        vlan_ranges: null
        mtu: null
      floating_network:
        enabled: true
        physnet: physnet1
        subnet:
          gateway: 192.168.3.1
          pool_end: 192.168.3.250
          pool_start: 192.168.3.100
          range: 192.168.3.0/24
    nova:
      live_migration_interface: bond0.1001
      images:
        backend: ceph
  ###########
  # Services
  ##########
    orchestration:
      heat:
        values:
          conf:
            heat:
              clients_heat:
                insecure: true
    tempest:
      tempest:
        values:
          conf:
            script: cat /etc/tempest/tempest.conf; tempest run --config-file /etc/tempest/tempest.conf
              --concurrency 4 --blacklist-file /etc/tempest/test-blacklist --regex
              test || true; stestr last --subunit > /var/lib/tempest/data/tempest_report
